<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find Business Opportunities</name>
   <tag></tag>
   <elementGuidId>3849d868-025d-44c9-b034-2a58e11353af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/div[3]/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.rBtn.sml.mouse-focus.focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Find Business Opportunities&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>809bc62b-35fc-4baa-b279-c2e1159b2c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://tenders.gov.au/atm</value>
      <webElementGuid>fc79ad09-3739-4cd2-9c09-fc954d8d13da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rBtn sml mouse-focus focus</value>
      <webElementGuid>2ae3c291-3fa5-4717-ac95-fe846f42c31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find Business Opportunities</value>
      <webElementGuid>5c97b7cf-3097-491d-9c8f-4cb34bc9851d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;boxEQH&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-md-8&quot;]/div[@class=&quot;rBox&quot;]/div[@class=&quot;home-buttons&quot;]/a[@class=&quot;rBtn sml mouse-focus focus&quot;]</value>
      <webElementGuid>25e92cea-72d6-4ad9-bb15-1e7b0e65b852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div[3]/div/div/div/div/a</value>
      <webElementGuid>8abbae17-f4f9-4c16-b2a7-8bd71c4859bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find Business Opportunities')]</value>
      <webElementGuid>0a1d16ca-8e1f-4cea-bd1b-028010a05ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Opportunities'])[1]/following::a[1]</value>
      <webElementGuid>7a40770f-a266-4553-b5c4-e6b6eea467b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AusTender Help and Information Centre.'])[1]/following::a[1]</value>
      <webElementGuid>e4bf7a2d-e41a-49c7-9f47-a12b0372472b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State and Territory Opportunties'])[1]/preceding::a[1]</value>
      <webElementGuid>e32d5e78-fb83-4901-8ae9-d9a21246cb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trading Partner Opportunities'])[1]/preceding::a[2]</value>
      <webElementGuid>70c5ef4f-0c97-47c0-b239-c0840ccf4c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find Business Opportunities']/parent::*</value>
      <webElementGuid>9cfa2e54-b5b7-4f6b-b579-7eb842dca483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://tenders.gov.au/atm']</value>
      <webElementGuid>e35242a1-17b8-4c98-91f1-8ff1857f9dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/a</value>
      <webElementGuid>5c9da74d-0d12-4216-bcc7-d18e9230755b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://tenders.gov.au/atm' and (text() = 'Find Business Opportunities' or . = 'Find Business Opportunities')]</value>
      <webElementGuid>40fbeb9a-fc35-443c-bfa1-df3cd11787fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
