<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Business Opportunities</name>
   <tag></tag>
   <elementGuidId>0ab65f82-d8b9-482c-827d-fc971a1603b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/div[3]/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Business Opportunities&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>14fa2760-76fa-49cf-9fef-c4efd10175eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>783e7768-44dd-4f04-ad2a-b6120f62a05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business Opportunities</value>
      <webElementGuid>a0bea98f-7adf-4585-b35d-a79e5b5bb86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;boxEQH&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-md-8&quot;]/div[@class=&quot;rBox&quot;]/h2[@class=&quot;title&quot;]</value>
      <webElementGuid>3b40eac5-2752-4cb8-9ba6-70dc3af6d77b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/div[3]/div/div/div/h2</value>
      <webElementGuid>f6e9c2df-aa41-4cd2-ae88-7d846dd6f31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AusTender Help and Information Centre.'])[1]/following::h2[1]</value>
      <webElementGuid>8910e34b-f766-4569-98ca-af89a2c7ae3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Business Opportunities'])[1]/preceding::h2[1]</value>
      <webElementGuid>086b4023-854b-4282-bfa3-f4fca631ec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State and Territory Opportunties'])[1]/preceding::h2[1]</value>
      <webElementGuid>26c1a60a-94b6-4d78-98dd-1a8f2c55eaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Business Opportunities']/parent::*</value>
      <webElementGuid>e5f15c36-791e-4875-a3bc-5467300634db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>27b3e0e1-29c3-4649-bdf2-87c94d0274b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Business Opportunities' or . = 'Business Opportunities')]</value>
      <webElementGuid>1aa0970d-2bee-4233-9c4c-4094a71e38ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
