<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CN3712064</name>
   <tag></tag>
   <elementGuidId>a217407c-dda5-4655-a3ea-637fe1f2ccae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div[3]/div[2]/article/div/div[2]/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mouse-focus.focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CN3712064&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5d5fa45-0093-4665-919d-5a4d864a4d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Cn/Show/e0f012ef-565d-4d00-b79c-e70f77b4d1bf</value>
      <webElementGuid>f66cd30b-4608-4e4d-9ae6-7ed7c9e2a225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mouse-focus focus</value>
      <webElementGuid>8f0c7e0e-4520-4800-89c8-46436baf5f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CN3712064</value>
      <webElementGuid>11b7a531-2e45-4b24-b952-fa43a21ea7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;boxEQH&quot;]/article[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;box boxW listInner&quot;]/div[@class=&quot;list-desc&quot;]/div[@class=&quot;list-desc-inner&quot;]/a[@class=&quot;mouse-focus focus&quot;]</value>
      <webElementGuid>5426b476-a3b0-46ef-af33-4da1be10c58b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div[3]/div[2]/article/div/div[2]/div/div[2]/div/a</value>
      <webElementGuid>320792b0-b97a-46bf-8c90-5aaf2495b93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CN3712064')])[2]</value>
      <webElementGuid>538e9445-bb5d-49b3-b7d7-167148cb4d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amends:'])[1]/following::a[1]</value>
      <webElementGuid>2806ea3b-db39-44f4-9daa-ceb5e5a21396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CN3712064-A1'])[1]/following::a[1]</value>
      <webElementGuid>e8e7f13e-2fda-40f5-9cf7-9805408416ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency:'])[2]/preceding::a[1]</value>
      <webElementGuid>4b2ad2c1-059f-4727-8aa9-8d72e265608f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australian Federal Police'])[1]/preceding::a[1]</value>
      <webElementGuid>2bc4ff87-2b1d-45ba-90fd-2ec003a74af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CN3712064']/parent::*</value>
      <webElementGuid>3cca2cb1-399a-4b6d-a9a6-8d56427c5ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Cn/Show/e0f012ef-565d-4d00-b79c-e70f77b4d1bf')]</value>
      <webElementGuid>b9fba5ed-989a-4c72-be45-4d38508827b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>49b39453-0c88-4373-8eb5-3e4ada0fc442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Cn/Show/e0f012ef-565d-4d00-b79c-e70f77b4d1bf' and (text() = 'CN3712064' or . = 'CN3712064')]</value>
      <webElementGuid>c902892b-06f4-4111-aaf4-9b5e2a2fef8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
