<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i</name>
   <tag></tag>
   <elementGuidId>50fc5bd2-de56-4758-9cf8-1255e0625073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='actions']/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;SearchButton&quot;] > i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f49e624c-679f-4cd1-afd1-9c1bdac627de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actions&quot;)/div[@class=&quot;col-sm-2 col-sm-push-10&quot;]/button[@class=&quot;rBtn fa-input btn-search mouse-focus focus&quot;]/i[1]</value>
      <webElementGuid>4cbd39a2-92d4-43b6-ac06-f8f050926963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/div/button/i</value>
      <webElementGuid>6b3ca666-6ad8-480e-a17c-f9626eea105d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/i</value>
      <webElementGuid>a3947c7a-51f4-4c0e-a47f-7e51acf7f37b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
