<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_South Bandiana Building Works, VIC</name>
   <tag></tag>
   <elementGuidId>0fb57e27-2892-4b02-beff-ef8244155daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pp-a0c45b89-3ec4-4f75-aa0f-d05fa95bcf84']/div[8]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mouse-focus.focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;South Bandiana Building Works, VIC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6fdf810f-fb55-491d-af31-64601ac1131b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Atm/Show/7e7adc8a-4d85-4972-85ec-9a72aede61c4</value>
      <webElementGuid>b54b6e98-1b4b-4f1a-bc4d-e4f9082ece6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mouse-focus focus</value>
      <webElementGuid>5c52c169-eadf-4bc5-9451-ea98c320ae1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>South Bandiana Building Works, VIC</value>
      <webElementGuid>6cb4494d-41b7-4e01-ba6b-6ab2bdc592a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-a0c45b89-3ec4-4f75-aa0f-d05fa95bcf84&quot;)/div[@class=&quot;list-desc&quot;]/div[@class=&quot;list-desc-inner&quot;]/a[@class=&quot;mouse-focus focus&quot;]</value>
      <webElementGuid>44b88271-b05d-4329-8978-096777fdfd8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-a0c45b89-3ec4-4f75-aa0f-d05fa95bcf84']/div[8]/div/a</value>
      <webElementGuid>2fdf62e0-9a05-426a-b9b3-c54eabf28a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'South Bandiana Building Works, VIC')]</value>
      <webElementGuid>b14bb0f8-c996-499f-9828-c9f0f54cbe0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change to description and estimated date of release'])[1]/following::a[1]</value>
      <webElementGuid>0fe75399-91e7-481f-8b28-a56bf09f3597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact:'])[1]/preceding::a[1]</value>
      <webElementGuid>4c18cdd5-a90a-415a-8af0-4536bcce9646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='South Bandiana Building Works, VIC']/parent::*</value>
      <webElementGuid>e1e98539-acec-49e2-a396-7910521c6b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Atm/Show/7e7adc8a-4d85-4972-85ec-9a72aede61c4')]</value>
      <webElementGuid>4df441b4-f877-45d1-9cd2-e5619415a8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/a</value>
      <webElementGuid>86ef2087-eeb2-42d5-8b82-56e00c2759a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Atm/Show/7e7adc8a-4d85-4972-85ec-9a72aede61c4' and (text() = 'South Bandiana Building Works, VIC' or . = 'South Bandiana Building Works, VIC')]</value>
      <webElementGuid>3a63b962-29e6-4b7a-bdb2-36a906042b16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
