<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort</name>
   <tag></tag>
   <elementGuidId>e475b7f5-c59e-4471-a2cf-bd9069a50ba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form-sort-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-sort-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sort&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9234ae57-a529-45a3-866f-2fcc7a0a9971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bad6f5c4-1972-4517-9355-f299a3aec32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sort</value>
      <webElementGuid>5d15f418-8afd-43b5-ba5d-0197cf008351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-sort-1</value>
      <webElementGuid>3a38cb7f-a907-4613-9522-c457161db612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit mouse-focus focus</value>
      <webElementGuid>06cbe5a3-b6d9-427c-9954-8ecafc01998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort</value>
      <webElementGuid>db52b6dc-1aad-4608-b4f4-0a708345a2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-sort-1&quot;)</value>
      <webElementGuid>f1c84aec-c038-4609-8ab0-0d1c615b0048</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form-sort-1']</value>
      <webElementGuid>3117e4f8-6a70-459d-aee2-5bfc45bb6908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sortForm']/div/div/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>9886e026-69da-46cf-9666-204cfbc76d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency'])[1]/following::button[1]</value>
      <webElementGuid>2f46701b-51e9-47d0-806b-80206bd02fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[2]/following::button[1]</value>
      <webElementGuid>849737c6-f4c7-4ddb-94d8-19feb1bffb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EST10524 South Bandiana Building Works'])[1]/preceding::button[1]</value>
      <webElementGuid>5f13a2ba-09f9-4988-ad07-1a78d1f9fede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must be a logged in AusTender registered user to watch a planned procurement'])[1]/preceding::button[1]</value>
      <webElementGuid>15dba958-7c2a-408e-842d-10e5ead9a895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sort']/parent::*</value>
      <webElementGuid>40747601-39e2-41fb-acdd-469b5d63f030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>333a38e1-17f1-496b-be92-64169894e778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'sort' and @id = 'form-sort-1' and (text() = 'Sort' or . = 'Sort')]</value>
      <webElementGuid>63123505-8e45-4f51-b177-9cb3dc9117f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
