<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Relevance                           _59b6fc</name>
   <tag></tag>
   <elementGuidId>8da11a23-a8ef-4733-b1a0-c87c5ae61171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='form-OrderBy-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-OrderBy-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sort By&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80c0fc5c-bde7-4685-b44d-1f57e9bf0453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OrderBy</value>
      <webElementGuid>0e7ce7c1-a819-482b-884d-b8a6e866558e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker</value>
      <webElementGuid>c95c02d7-78a8-4f1f-914d-f88ca8dabb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-OrderBy-1</value>
      <webElementGuid>0a029407-9354-4341-8276-72d76f122d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e247380b-23da-4c14-b66f-9303fa9d5195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>957cb54d-d236-4ce1-a4be-ef2d96c56699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Relevance
                                                Last Updated
                                                Title
                                                Agency
                                    </value>
      <webElementGuid>59729f97-6e12-4677-a57a-e273ebdd90b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-OrderBy-1&quot;)</value>
      <webElementGuid>948000dc-2383-4fe7-b996-2d4a4d5f3ea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form-OrderBy-1']</value>
      <webElementGuid>d9e019bf-99fe-4990-a5a6-a4e2a7334ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sortForm']/div/div/div/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>4a374845-3ad0-4ecc-82d2-26ec938d2dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency'])[1]/following::select[1]</value>
      <webElementGuid>efa5804c-84ac-4c71-9d31-f2a4877bdf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::select[1]</value>
      <webElementGuid>08a2f131-8d0c-4998-9aba-8407061427ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/preceding::select[1]</value>
      <webElementGuid>ef5fa4dd-b0f2-493d-b152-bf3fde36e4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EST10524 South Bandiana Building Works'])[1]/preceding::select[1]</value>
      <webElementGuid>7ee15a53-942b-4ab1-a67a-d11ebb75dce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>13ebf189-5e7a-445a-b218-5ba3e103912e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'OrderBy' and @id = 'form-OrderBy-1' and (text() = '
                                                Relevance
                                                Last Updated
                                                Title
                                                Agency
                                    ' or . = '
                                                Relevance
                                                Last Updated
                                                Title
                                                Agency
                                    ')]</value>
      <webElementGuid>235664ba-4bb2-4031-a57e-7937151fe3e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
