<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SON4139337</name>
   <tag></tag>
   <elementGuidId>ecf8b925-894e-48f9-bfe6-47345df1c99b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/article/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mouse-focus.focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SON4139337&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7200d519-0c63-4c78-b2c5-5b6c7dc482c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Son/Show/b2038269-5ff4-4231-b114-59720b03ac6a</value>
      <webElementGuid>4d8eaac7-6727-4d77-bcba-889b67f85898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mouse-focus focus</value>
      <webElementGuid>db4ece63-4dcd-4ca9-9e62-0218fe804b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SON4139337</value>
      <webElementGuid>54c4e3b2-f496-41f5-9654-545435443549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container&quot;]/article[1]/div[@class=&quot;boxEQH&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;box boxW listInner&quot;]/div[@class=&quot;list-desc&quot;]/div[@class=&quot;list-desc-inner&quot;]/a[@class=&quot;mouse-focus focus&quot;]</value>
      <webElementGuid>a1815fe8-5aa2-424b-ab09-c6a212be4ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/article/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>6324c09d-7459-4206-bcd4-15345b6c8c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SON4139337')]</value>
      <webElementGuid>1ec03603-91b3-44d6-981b-c836f31a17d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SON ID:'])[1]/following::a[1]</value>
      <webElementGuid>105d2a54-c163-417d-b8fe-7137d5a9e4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/following::a[1]</value>
      <webElementGuid>69130e02-7d69-4694-8ce0-ce68c60fb723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Date:'])[1]/preceding::a[1]</value>
      <webElementGuid>274c425b-db14-4bc8-bf75-3fc74602277f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency:'])[1]/preceding::a[1]</value>
      <webElementGuid>ed3dc426-b6d3-4009-a9d7-6fd79506b180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SON4139337']/parent::*</value>
      <webElementGuid>710ce060-2859-49b6-b938-5ac78dbb8ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Son/Show/b2038269-5ff4-4231-b114-59720b03ac6a')]</value>
      <webElementGuid>15467353-2285-437f-84ba-24624e21d448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>a8e5a3fa-31de-454e-a071-cea6aacdeb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Son/Show/b2038269-5ff4-4231-b114-59720b03ac6a' and (text() = 'SON4139337' or . = 'SON4139337')]</value>
      <webElementGuid>f85cbaac-a7b8-4f30-8350-52f9f349d86f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
